export type FilmGenre =
  | "Action"
  | "Drama"
  | "Comedy"
  | "Thriller"
  | "SciFi"
  | "Horror"
  | "Documentary"
  | "Romance"
  | "Animation"
  | "Crime";

export type MediaType = "film" | "tv";

export interface FilmRatings {
  plot: number;
  acting: number;
  cinematography: number;
  soundtrack: number;
  dialogue: number;
  rewatch: number;
}

export interface Film {
  title: string;
  director: string;
  descriptionKey: string;
  coverImage?: string;
  dateWatched: string;
  yearReleased?: number;
  genreKey?: FilmGenre;
  mediaType: MediaType;
  seasons?: number;
  ratings: FilmRatings;
  reviewKey: string;
  link?: string;
  favorite?: boolean;
}

export const filmGenreKeys: FilmGenre[] = [
  "Action",
  "Drama",
  "Comedy",
  "Thriller",
  "SciFi",
  "Horror",
  "Documentary",
  "Romance",
  "Animation",
  "Crime",
];

export const ratingCategories: (keyof FilmRatings)[] = [
  "plot",
  "acting",
  "cinematography",
  "soundtrack",
  "dialogue",
  "rewatch",
];

export function computeOverallRating(ratings: FilmRatings): number {
  const values = Object.values(ratings);
  const avg = values.reduce((sum, v) => sum + v, 0) / values.length;
  return Math.round(avg * 10) / 10;
}

export function getStats(filmsList: Film[]) {
  if (filmsList.length === 0)
    return { count: 0, average: 0, best: null, worst: null };

  const withRatings = filmsList.map((f) => ({
    film: f,
    overall: computeOverallRating(f.ratings),
  }));

  const avg =
    withRatings.reduce((sum, r) => sum + r.overall, 0) / withRatings.length;

  const sorted = [...withRatings].sort((a, b) => b.overall - a.overall);

  return {
    count: filmsList.length,
    average: Math.round(avg * 10) / 10,
    best: sorted[0],
    worst: sorted[sorted.length - 1],
  };
}

export const films: Film[] = [
  // ── FINANCE / WALL STREET ──────────────────────────────────
  {
    title: "Margin Call",
    director: "J.C. Chandor",
    descriptionKey: "marginCallDescription",
    coverImage: "/images/films/margin-call.jpg",
    dateWatched: "2024-02-15",
    yearReleased: 2011,
    genreKey: "Drama",
    mediaType: "film",
    ratings: {
      plot: 8,
      acting: 9,
      cinematography: 7,
      soundtrack: 6,
      dialogue: 9,
      rewatch: 7,
    },
    reviewKey: "marginCallReview",
    link: "https://www.imdb.com/title/tt1615065/",
    favorite: false,
  },
  {
    title: "The Big Short",
    director: "Adam McKay",
    descriptionKey: "theBigShortDescription",
    coverImage: "/images/films/the-big-short.jpg",
    dateWatched: "2024-01-20",
    yearReleased: 2015,
    genreKey: "Drama",
    mediaType: "film",
    ratings: {
      plot: 9,
      acting: 9,
      cinematography: 7,
      soundtrack: 7,
      dialogue: 10,
      rewatch: 8,
    },
    reviewKey: "theBigShortReview",
    link: "https://www.imdb.com/title/tt1596363/",
    favorite: true,
  },
  {
    title: "The Wolf of Wall Street",
    director: "Martin Scorsese",
    descriptionKey: "theWolfOfWallStreetDescription",
    coverImage: "/images/films/wolf-of-wall-street.png",
    dateWatched: "2023-06-12",
    yearReleased: 2013,
    genreKey: "Comedy",
    mediaType: "film",
    ratings: {
      plot: 9,
      acting: 10,
      cinematography: 8,
      soundtrack: 8,
      dialogue: 10,
      rewatch: 9,
    },
    reviewKey: "theWolfOfWallStreetReview",
    link: "https://www.imdb.com/title/tt0993846/",
    favorite: true,
  },
  {
    title: "Billions",
    director: "Brian Koppelman & David Levien",
    descriptionKey: "billionsDescription",
    coverImage: "/images/films/billions.jpg",
    dateWatched: "2024-11-10",
    yearReleased: 2016,
    genreKey: "Drama",
    mediaType: "tv",
    seasons: 7,
    ratings: {
      plot: 8,
      acting: 9,
      cinematography: 7,
      soundtrack: 6,
      dialogue: 9,
      rewatch: 7,
    },
    reviewKey: "billionsReview",
    link: "https://www.imdb.com/title/tt4270492/",
    favorite: false,
  },
  {
    title: "Gold",
    director: "Stephen Gaghan",
    descriptionKey: "goldDescription",
    coverImage: "/images/films/gold.jpg",
    dateWatched: "2024-03-05",
    yearReleased: 2016,
    genreKey: "Drama",
    mediaType: "film",
    ratings: {
      plot: 7,
      acting: 8,
      cinematography: 7,
      soundtrack: 6,
      dialogue: 7,
      rewatch: 5,
    },
    reviewKey: "goldReview",
    link: "https://www.imdb.com/title/tt1800302/",
    favorite: false,
  },
  {
    title: "War Dogs",
    director: "Todd Phillips",
    descriptionKey: "warDogsDescription",
    coverImage: "/images/films/war-dogs.jpg",
    dateWatched: "2024-04-20",
    yearReleased: 2016,
    genreKey: "Comedy",
    mediaType: "film",
    ratings: {
      plot: 8,
      acting: 8,
      cinematography: 7,
      soundtrack: 7,
      dialogue: 8,
      rewatch: 7,
    },
    reviewKey: "warDogsReview",
    link: "https://www.imdb.com/title/tt2005151/",
    favorite: false,
  },
  {
    title: "Uncut Gems",
    director: "Josh & Benny Safdie",
    descriptionKey: "uncutGemsDescription",
    coverImage: "/images/films/uncut-gems.jpg",
    dateWatched: "2024-01-08",
    yearReleased: 2019,
    genreKey: "Thriller",
    mediaType: "film",
    ratings: {
      plot: 8,
      acting: 9,
      cinematography: 8,
      soundtrack: 8,
      dialogue: 8,
      rewatch: 6,
    },
    reviewKey: "uncutGemsReview",
    link: "https://www.imdb.com/title/tt5727208/",
    favorite: false,
  },
  {
    title: "Catch Me If You Can",
    director: "Steven Spielberg",
    descriptionKey: "catchMeIfYouCanDescription",
    coverImage: "/images/films/catch-me-if-you-can.jpg",
    dateWatched: "2023-07-15",
    yearReleased: 2002,
    genreKey: "Crime",
    mediaType: "film",
    ratings: {
      plot: 9,
      acting: 9,
      cinematography: 8,
      soundtrack: 8,
      dialogue: 8,
      rewatch: 9,
    },
    reviewKey: "catchMeIfYouCanReview",
    link: "https://www.imdb.com/title/tt0264464/",
    favorite: true,
  },

  // ── TECH / STARTUP ─────────────────────────────────────────
  {
    title: "WeCrashed",
    director: "Lee Eisenberg & Drew Crevello",
    descriptionKey: "wecrashedDescription",
    coverImage: "/images/films/wecrashed.jpg",
    dateWatched: "2024-04-10",
    yearReleased: 2022,
    genreKey: "Drama",
    mediaType: "tv",
    seasons: 1,
    ratings: {
      plot: 8,
      acting: 9,
      cinematography: 7,
      soundtrack: 6,
      dialogue: 8,
      rewatch: 6,
    },
    reviewKey: "wecrashedReview",
    link: "https://www.imdb.com/title/tt12005128/",
    favorite: false,
  },

  // ── TARANTINO ──────────────────────────────────────────────
  {
    title: "Django Unchained",
    director: "Quentin Tarantino",
    descriptionKey: "djangoUnchainedDescription",
    coverImage: "/images/films/django-unchained.jpg",
    dateWatched: "2023-05-10",
    yearReleased: 2012,
    genreKey: "Action",
    mediaType: "film",
    ratings: {
      plot: 9,
      acting: 10,
      cinematography: 9,
      soundtrack: 9,
      dialogue: 10,
      rewatch: 9,
    },
    reviewKey: "djangoUnchainedReview",
    link: "https://www.imdb.com/title/tt1853728/",
    favorite: true,
  },
  {
    title: "Pulp Fiction",
    director: "Quentin Tarantino",
    descriptionKey: "pulpFictionDescription",
    coverImage: "/images/films/pulp-fiction.jpeg",
    dateWatched: "2023-04-18",
    yearReleased: 1994,
    genreKey: "Crime",
    mediaType: "film",
    ratings: {
      plot: 9,
      acting: 10,
      cinematography: 8,
      soundtrack: 10,
      dialogue: 10,
      rewatch: 9,
    },
    reviewKey: "pulpFictionReview",
    link: "https://www.imdb.com/title/tt0110912/",
    favorite: true,
  },
  {
    title: "Inglourious Basterds",
    director: "Quentin Tarantino",
    descriptionKey: "inglouriousBasterdsDescription",
    coverImage: "/images/films/inglourious-basterds.jpg",
    dateWatched: "2023-06-25",
    yearReleased: 2009,
    genreKey: "Action",
    mediaType: "film",
    ratings: {
      plot: 9,
      acting: 10,
      cinematography: 9,
      soundtrack: 8,
      dialogue: 10,
      rewatch: 8,
    },
    reviewKey: "inglouriousBasterdsReview",
    link: "https://www.imdb.com/title/tt0361748/",
    favorite: true,
  },

  // ── BRITISH CRIME / DRAMA ──────────────────────────────────
  {
    title: "Kidulthood",
    director: "Menhaj Huda",
    descriptionKey: "kidulthoodDescription",
    coverImage: "/images/films/kidulthood.jpg",
    dateWatched: "2023-03-01",
    yearReleased: 2006,
    genreKey: "Drama",
    mediaType: "film",
    ratings: {
      plot: 7,
      acting: 7,
      cinematography: 6,
      soundtrack: 7,
      dialogue: 8,
      rewatch: 6,
    },
    reviewKey: "kidulthoodReview",
    link: "https://www.imdb.com/title/tt0435680/",
    favorite: false,
  },
  {
    title: "Adulthood",
    director: "Noel Clarke",
    descriptionKey: "adulthoodDescription",
    coverImage: "/images/films/adulthood.jpg",
    dateWatched: "2023-03-05",
    yearReleased: 2008,
    genreKey: "Drama",
    mediaType: "film",
    ratings: {
      plot: 7,
      acting: 7,
      cinematography: 6,
      soundtrack: 7,
      dialogue: 7,
      rewatch: 5,
    },
    reviewKey: "adulthoodReview",
    link: "https://www.imdb.com/title/tt1001508/",
    favorite: false,
  },
  {
    title: "Brotherhood",
    director: "Noel Clarke",
    descriptionKey: "brotherhoodDescription",
    coverImage: "/images/films/brotherhood.jpg",
    dateWatched: "2023-03-10",
    yearReleased: 2016,
    genreKey: "Drama",
    mediaType: "film",
    ratings: {
      plot: 6,
      acting: 7,
      cinematography: 7,
      soundtrack: 6,
      dialogue: 7,
      rewatch: 4,
    },
    reviewKey: "brotherhoodReview",
    link: "https://www.imdb.com/title/tt3516568/",
    favorite: false,
  },
  {
    title: "Rise of the Footsoldier",
    director: "Julian Gilbey",
    descriptionKey: "riseOfTheFootsoldierDescription",
    coverImage: "/images/films/rise-of-the-footsoldier.jpg",
    dateWatched: "2023-08-20",
    yearReleased: 2007,
    genreKey: "Crime",
    mediaType: "film",
    ratings: {
      plot: 7,
      acting: 7,
      cinematography: 6,
      soundtrack: 6,
      dialogue: 7,
      rewatch: 5,
    },
    reviewKey: "riseOfTheFootsoldierReview",
    link: "https://www.imdb.com/title/tt0901507/",
    favorite: false,
  },
  {
    title: "Top Boy: Summerhouse",
    director: "Ronan Bennett",
    descriptionKey: "topBoySummerhouseDescription",
    coverImage: "/images/films/top-boy-summerhouse.jpeg",
    dateWatched: "2023-09-01",
    yearReleased: 2011,
    genreKey: "Crime",
    mediaType: "tv",
    seasons: 2,
    ratings: {
      plot: 9,
      acting: 9,
      cinematography: 7,
      soundtrack: 7,
      dialogue: 9,
      rewatch: 7,
    },
    reviewKey: "topBoySummerhouseReview",
    link: "https://www.imdb.com/title/tt1830379/",
    favorite: true,
  },
  {
    title: "Top Boy",
    director: "Ronan Bennett",
    descriptionKey: "topBoyDescription",
    coverImage: "/images/films/top-boy.jpg",
    dateWatched: "2024-01-15",
    yearReleased: 2019,
    genreKey: "Crime",
    mediaType: "tv",
    seasons: 3,
    ratings: {
      plot: 8,
      acting: 9,
      cinematography: 8,
      soundtrack: 7,
      dialogue: 9,
      rewatch: 7,
    },
    reviewKey: "topBoyReview",
    link: "https://www.imdb.com/title/tt1830379/",
    favorite: true,
  },
  {
    title: "Peaky Blinders",
    director: "Steven Knight",
    descriptionKey: "peakyBlindersDescription",
    coverImage: "/images/films/peaky-blinders.png",
    dateWatched: "2024-02-28",
    yearReleased: 2013,
    genreKey: "Crime",
    mediaType: "tv",
    seasons: 6,
    ratings: {
      plot: 9,
      acting: 10,
      cinematography: 9,
      soundtrack: 9,
      dialogue: 9,
      rewatch: 8,
    },
    reviewKey: "peakyBlindersReview",
    link: "https://www.imdb.com/title/tt2442560/",
    favorite: true,
  },
  {
    title: "Snatch",
    director: "Guy Ritchie",
    descriptionKey: "snatchDescription",
    coverImage: "/images/films/snatch.jpg",
    dateWatched: "2023-10-12",
    yearReleased: 2000,
    genreKey: "Crime",
    mediaType: "film",
    ratings: {
      plot: 8,
      acting: 9,
      cinematography: 8,
      soundtrack: 8,
      dialogue: 10,
      rewatch: 9,
    },
    reviewKey: "snatchReview",
    link: "https://www.imdb.com/title/tt0208092/",
    favorite: true,
  },
  {
    title: "Lock, Stock and Two Smoking Barrels",
    director: "Guy Ritchie",
    descriptionKey: "lockStockAndTwoSmokingBarrelsDescription",
    coverImage: "/images/films/lock-stock.jpg",
    dateWatched: "2023-10-18",
    yearReleased: 1998,
    genreKey: "Crime",
    mediaType: "film",
    ratings: {
      plot: 8,
      acting: 8,
      cinematography: 7,
      soundtrack: 8,
      dialogue: 10,
      rewatch: 8,
    },
    reviewKey: "lockStockAndTwoSmokingBarrelsReview",
    link: "https://www.imdb.com/title/tt0120735/",
    favorite: true,
  },

  // ── BREAKING BAD UNIVERSE ──────────────────────────────────
  {
    title: "Breaking Bad",
    director: "Vince Gilligan",
    descriptionKey: "breakingBadDescription",
    coverImage: "/images/films/breaking-bad.jpg",
    dateWatched: "2024-11-20",
    yearReleased: 2008,
    genreKey: "Crime",
    mediaType: "tv",
    seasons: 5,
    ratings: {
      plot: 10,
      acting: 10,
      cinematography: 9,
      soundtrack: 8,
      dialogue: 10,
      rewatch: 9,
    },
    reviewKey: "breakingBadReview",
    link: "https://www.imdb.com/title/tt0903747/",
    favorite: true,
  },
  {
    title: "Better Call Saul",
    director: "Vince Gilligan & Peter Gould",
    descriptionKey: "betterCallSaulDescription",
    coverImage: "/images/films/better-call-saul.jpg",
    dateWatched: "2024-12-01",
    yearReleased: 2015,
    genreKey: "Crime",
    mediaType: "tv",
    seasons: 6,
    ratings: {
      plot: 9,
      acting: 10,
      cinematography: 10,
      soundtrack: 8,
      dialogue: 9,
      rewatch: 8,
    },
    reviewKey: "betterCallSaulReview",
    link: "https://www.imdb.com/title/tt3032476/",
    favorite: true,
  },
  {
    title: "El Camino: A Breaking Bad Movie",
    director: "Vince Gilligan",
    descriptionKey: "elCaminoABreakingBadMovieDescription",
    coverImage: "/images/films/el-camino.jpg",
    dateWatched: "2024-12-05",
    yearReleased: 2019,
    genreKey: "Crime",
    mediaType: "film",
    ratings: {
      plot: 7,
      acting: 9,
      cinematography: 9,
      soundtrack: 7,
      dialogue: 7,
      rewatch: 5,
    },
    reviewKey: "elCaminoABreakingBadMovieReview",
    link: "https://www.imdb.com/title/tt9243946/",
    favorite: false,
  },

  // ── SCI-FI / THRILLER ──────────────────────────────────────
  {
    title: "Interstellar",
    director: "Christopher Nolan",
    descriptionKey: "interstellarDescription",
    coverImage: "/images/films/interstellar.jpg",
    dateWatched: "2024-03-10",
    yearReleased: 2014,
    genreKey: "SciFi",
    mediaType: "film",
    ratings: {
      plot: 9,
      acting: 9,
      cinematography: 10,
      soundtrack: 10,
      dialogue: 8,
      rewatch: 9,
    },
    reviewKey: "interstellarReview",
    link: "https://www.imdb.com/title/tt0816692/",
    favorite: true,
  },
  {
    title: "Parasite",
    director: "Bong Joon-ho",
    descriptionKey: "parasiteDescription",
    coverImage: "/images/films/parasite.jpg",
    dateWatched: "2025-01-12",
    yearReleased: 2019,
    genreKey: "Thriller",
    mediaType: "film",
    ratings: {
      plot: 10,
      acting: 9,
      cinematography: 9,
      soundtrack: 8,
      dialogue: 8,
      rewatch: 8,
    },
    reviewKey: "parasiteReview",
    link: "https://www.imdb.com/title/tt6751668/",
    favorite: true,
  },
  {
    title: "Black Mirror",
    director: "Charlie Brooker",
    descriptionKey: "blackMirrorDescription",
    coverImage: "/images/films/black-mirror.jpg",
    dateWatched: "2024-06-01",
    yearReleased: 2011,
    genreKey: "SciFi",
    mediaType: "tv",
    seasons: 7,
    ratings: {
      plot: 9,
      acting: 8,
      cinematography: 8,
      soundtrack: 7,
      dialogue: 8,
      rewatch: 7,
    },
    reviewKey: "blackMirrorReview",
    link: "https://www.imdb.com/title/tt2085059/",
    favorite: true,
  },
  {
    title: "Oblivion",
    director: "Joseph Kosinski",
    descriptionKey: "oblivionDescription",
    coverImage: "/images/films/oblivion.jpg",
    dateWatched: "2024-05-22",
    yearReleased: 2013,
    genreKey: "SciFi",
    mediaType: "film",
    ratings: {
      plot: 7,
      acting: 7,
      cinematography: 9,
      soundtrack: 8,
      dialogue: 6,
      rewatch: 6,
    },
    reviewKey: "oblivionReview",
    link: "https://www.imdb.com/title/tt1483013/",
    favorite: false,
  },
  {
    title: "Ex Machina",
    director: "Alex Garland",
    descriptionKey: "exMachinaDescription",
    coverImage: "/images/films/ex-machina.jpg",
    dateWatched: "2024-06-15",
    yearReleased: 2014,
    genreKey: "SciFi",
    mediaType: "film",
    ratings: {
      plot: 9,
      acting: 9,
      cinematography: 9,
      soundtrack: 8,
      dialogue: 9,
      rewatch: 8,
    },
    reviewKey: "exMachinaReview",
    link: "https://www.imdb.com/title/tt0470752/",
    favorite: true,
  },
  {
    title: "I Am Mother",
    director: "Grant Sputore",
    descriptionKey: "iAmMotherDescription",
    coverImage: "/images/films/i-am-mother.jpg",
    dateWatched: "2024-06-20",
    yearReleased: 2019,
    genreKey: "SciFi",
    mediaType: "film",
    ratings: {
      plot: 8,
      acting: 7,
      cinematography: 7,
      soundtrack: 6,
      dialogue: 7,
      rewatch: 5,
    },
    reviewKey: "iAmMotherReview",
    link: "https://www.imdb.com/title/tt6292852/",
    favorite: false,
  },
  {
    title: "Snowpiercer",
    director: "Bong Joon-ho",
    descriptionKey: "snowpiercerDescription",
    coverImage: "/images/films/snowpiercer.jpg",
    dateWatched: "2024-07-01",
    yearReleased: 2013,
    genreKey: "SciFi",
    mediaType: "film",
    ratings: {
      plot: 8,
      acting: 8,
      cinematography: 8,
      soundtrack: 7,
      dialogue: 7,
      rewatch: 7,
    },
    reviewKey: "snowpiercerReview",
    link: "https://www.imdb.com/title/tt1706620/",
    favorite: false,
  },
  {
    title: "Get Out",
    director: "Jordan Peele",
    descriptionKey: "getOutDescription",
    coverImage: "/images/films/get-out.jpg",
    dateWatched: "2024-02-20",
    yearReleased: 2017,
    genreKey: "Thriller",
    mediaType: "film",
    ratings: {
      plot: 9,
      acting: 9,
      cinematography: 8,
      soundtrack: 8,
      dialogue: 8,
      rewatch: 7,
    },
    reviewKey: "getOutReview",
    link: "https://www.imdb.com/title/tt5052448/",
    favorite: true,
  },
  {
    title: "Prisoners",
    director: "Denis Villeneuve",
    descriptionKey: "prisonersDescription",
    coverImage: "/images/films/prisoners.jpg",
    dateWatched: "2024-03-25",
    yearReleased: 2013,
    genreKey: "Thriller",
    mediaType: "film",
    ratings: {
      plot: 9,
      acting: 10,
      cinematography: 9,
      soundtrack: 8,
      dialogue: 8,
      rewatch: 7,
    },
    reviewKey: "prisonersReview",
    link: "https://www.imdb.com/title/tt1392214/",
    favorite: true,
  },
  {
    title: "Bird Box",
    director: "Susanne Bier",
    descriptionKey: "birdBoxDescription",
    coverImage: "/images/films/bird-box.jpg",
    dateWatched: "2024-01-30",
    yearReleased: 2018,
    genreKey: "Thriller",
    mediaType: "film",
    ratings: {
      plot: 7,
      acting: 7,
      cinematography: 7,
      soundtrack: 6,
      dialogue: 6,
      rewatch: 5,
    },
    reviewKey: "birdBoxReview",
    link: "https://www.imdb.com/title/tt2737304/",
    favorite: false,
  },
  {
    title: "The Platform",
    director: "Galder Gaztelu-Urrutia",
    descriptionKey: "thePlatformDescription",
    coverImage: "/images/films/the-platform.jpg",
    dateWatched: "2024-08-05",
    yearReleased: 2019,
    genreKey: "Thriller",
    mediaType: "film",
    ratings: {
      plot: 8,
      acting: 7,
      cinematography: 7,
      soundtrack: 6,
      dialogue: 7,
      rewatch: 6,
    },
    reviewKey: "thePlatformReview",
    link: "https://www.imdb.com/title/tt8228288/",
    favorite: false,
  },
  {
    title: "The Platform 2",
    director: "Galder Gaztelu-Urrutia",
    descriptionKey: "thePlatform2Description",
    coverImage: "/images/films/the-platform-2.jpg",
    dateWatched: "2024-10-15",
    yearReleased: 2024,
    genreKey: "Thriller",
    mediaType: "film",
    ratings: {
      plot: 6,
      acting: 6,
      cinematography: 7,
      soundtrack: 6,
      dialogue: 6,
      rewatch: 4,
    },
    reviewKey: "thePlatform2Review",
    link: "https://www.imdb.com/title/tt20370776/",
    favorite: false,
  },
  {
    title: "Glass Onion: A Knives Out Mystery",
    director: "Rian Johnson",
    descriptionKey: "glassOnionAKnivesOutMysteryDescription",
    coverImage: "/images/films/glass-onion.jpg",
    dateWatched: "2024-05-10",
    yearReleased: 2022,
    genreKey: "Thriller",
    mediaType: "film",
    ratings: {
      plot: 8,
      acting: 9,
      cinematography: 8,
      soundtrack: 7,
      dialogue: 9,
      rewatch: 7,
    },
    reviewKey: "glassOnionAKnivesOutMysteryReview",
    link: "https://www.imdb.com/title/tt11564570/",
    favorite: false,
  },
  {
    title: "Don't Look Up",
    director: "Adam McKay",
    descriptionKey: "dontLookUpDescription",
    coverImage: "/images/films/dont-look-up.jpg",
    dateWatched: "2024-03-15",
    yearReleased: 2021,
    genreKey: "Comedy",
    mediaType: "film",
    ratings: {
      plot: 8,
      acting: 9,
      cinematography: 7,
      soundtrack: 7,
      dialogue: 8,
      rewatch: 6,
    },
    reviewKey: "dontLookUpReview",
    link: "https://www.imdb.com/title/tt11286314/",
    favorite: false,
  },

  // ── DRAMA / EMOTIONAL ──────────────────────────────────────
  {
    title: "The Perks of Being a Wallflower",
    director: "Stephen Chbosky",
    descriptionKey: "thePerksOfBeingAWallflowerDescription",
    coverImage: "/images/films/perks-wallflower.jpg",
    dateWatched: "2023-09-20",
    yearReleased: 2012,
    genreKey: "Drama",
    mediaType: "film",
    ratings: {
      plot: 8,
      acting: 8,
      cinematography: 7,
      soundtrack: 9,
      dialogue: 8,
      rewatch: 7,
    },
    reviewKey: "thePerksOfBeingAWallflowerReview",
    link: "https://www.imdb.com/title/tt1659337/",
    favorite: false,
  },
  {
    title: "Titanic",
    director: "James Cameron",
    descriptionKey: "titanicDescription",
    coverImage: "/images/films/titanic.jpg",
    dateWatched: "2023-02-14",
    yearReleased: 1997,
    genreKey: "Romance",
    mediaType: "film",
    ratings: {
      plot: 8,
      acting: 8,
      cinematography: 10,
      soundtrack: 10,
      dialogue: 7,
      rewatch: 7,
    },
    reviewKey: "titanicReview",
    link: "https://www.imdb.com/title/tt0120338/",
    favorite: false,
  },
  {
    title: "The Pursuit of Happyness",
    director: "Gabriele Muccino",
    descriptionKey: "thePursuitOfHappynessDescription",
    coverImage: "/images/films/pursuit-of-happyness.jpg",
    dateWatched: "2023-11-05",
    yearReleased: 2006,
    genreKey: "Drama",
    mediaType: "film",
    ratings: {
      plot: 8,
      acting: 10,
      cinematography: 7,
      soundtrack: 7,
      dialogue: 7,
      rewatch: 8,
    },
    reviewKey: "thePursuitOfHappynessReview",
    link: "https://www.imdb.com/title/tt0454921/",
    favorite: true,
  },
  {
    title: "The Boy in the Striped Pyjamas",
    director: "Mark Herman",
    descriptionKey: "theBoyInTheStripedPyjamasDescription",
    coverImage: "/images/films/boy-in-the-striped-pyjamas.jpg",
    dateWatched: "2023-03-28",
    yearReleased: 2008,
    genreKey: "Drama",
    mediaType: "film",
    ratings: {
      plot: 9,
      acting: 8,
      cinematography: 7,
      soundtrack: 7,
      dialogue: 7,
      rewatch: 4,
    },
    reviewKey: "theBoyInTheStripedPyjamasReview",
    link: "https://www.imdb.com/title/tt0914798/",
    favorite: false,
  },
  {
    title: "Joker",
    director: "Todd Phillips",
    descriptionKey: "jokerDescription",
    coverImage: "/images/films/joker.jpg",
    dateWatched: "2024-09-15",
    yearReleased: 2019,
    genreKey: "Drama",
    mediaType: "film",
    ratings: {
      plot: 8,
      acting: 10,
      cinematography: 9,
      soundtrack: 9,
      dialogue: 8,
      rewatch: 7,
    },
    reviewKey: "jokerReview",
    link: "https://www.imdb.com/title/tt7286456/",
    favorite: false,
  },
  {
    title: "The Irishman",
    director: "Martin Scorsese",
    descriptionKey: "theIrishmanDescription",
    coverImage: "/images/films/the-irishman.jpg",
    dateWatched: "2024-07-08",
    yearReleased: 2019,
    genreKey: "Crime",
    mediaType: "film",
    ratings: {
      plot: 8,
      acting: 9,
      cinematography: 8,
      soundtrack: 7,
      dialogue: 9,
      rewatch: 5,
    },
    reviewKey: "theIrishmanReview",
    link: "https://www.imdb.com/title/tt1302006/",
    favorite: false,
  },
  {
    title: "Forrest Gump",
    director: "Robert Zemeckis",
    descriptionKey: "forrestGumpDescription",
    coverImage: "/images/films/forrest-gump.jpg",
    dateWatched: "2023-04-01",
    yearReleased: 1994,
    genreKey: "Drama",
    mediaType: "film",
    ratings: {
      plot: 9,
      acting: 10,
      cinematography: 8,
      soundtrack: 9,
      dialogue: 9,
      rewatch: 9,
    },
    reviewKey: "forrestGumpReview",
    link: "https://www.imdb.com/title/tt0109830/",
    favorite: true,
  },
  {
    title: "The Queen's Gambit",
    director: "Scott Frank & Allan Scott",
    descriptionKey: "theQueensGambitDescription",
    coverImage: "/images/films/queens-gambit.jpg",
    dateWatched: "2024-04-25",
    yearReleased: 2020,
    genreKey: "Drama",
    mediaType: "tv",
    seasons: 1,
    ratings: {
      plot: 9,
      acting: 9,
      cinematography: 9,
      soundtrack: 8,
      dialogue: 8,
      rewatch: 7,
    },
    reviewKey: "theQueensGambitReview",
    link: "https://www.imdb.com/title/tt10048342/",
    favorite: true,
  },
  {
    title: "Baby Reindeer",
    director: "Richard Gadd",
    descriptionKey: "babyReindeerDescription",
    coverImage: "/images/films/baby-reindeer.jpg",
    dateWatched: "2024-05-01",
    yearReleased: 2024,
    genreKey: "Drama",
    mediaType: "tv",
    seasons: 1,
    ratings: {
      plot: 9,
      acting: 10,
      cinematography: 7,
      soundtrack: 7,
      dialogue: 8,
      rewatch: 5,
    },
    reviewKey: "babyReindeerReview",
    link: "https://www.imdb.com/title/tt13649112/",
    favorite: false,
  },
  {
    title: "Dexter",
    director: "James Manos Jr.",
    descriptionKey: "dexterDescription",
    coverImage: "/images/films/dexter.jpg",
    dateWatched: "2024-08-15",
    yearReleased: 2006,
    genreKey: "Crime",
    mediaType: "tv",
    seasons: 8,
    ratings: {
      plot: 8,
      acting: 9,
      cinematography: 7,
      soundtrack: 7,
      dialogue: 8,
      rewatch: 7,
    },
    reviewKey: "dexterReview",
    link: "https://www.imdb.com/title/tt0773262/",
    favorite: false,
  },

  // ── DOCUMENTARIES ──────────────────────────────────────────
  {
    title: "Tiger King",
    director: "Eric Goode & Rebecca Chaiklin",
    descriptionKey: "tigerKingDescription",
    coverImage: "/images/films/tiger-king.jpg",
    dateWatched: "2024-03-20",
    yearReleased: 2020,
    genreKey: "Documentary",
    mediaType: "tv",
    seasons: 2,
    ratings: {
      plot: 8,
      acting: 7,
      cinematography: 6,
      soundtrack: 5,
      dialogue: 7,
      rewatch: 6,
    },
    reviewKey: "tigerKingReview",
    link: "https://www.imdb.com/title/tt11823076/",
    favorite: false,
  },
  {
    title: "Jimmy Savile: A British Horror Story",
    director: "Rowan Deacon",
    descriptionKey: "jimmySavileABritishHorrorStoryDescription",
    coverImage: "/images/films/jimmy-savile.jpg",
    dateWatched: "2024-04-05",
    yearReleased: 2022,
    genreKey: "Documentary",
    mediaType: "tv",
    seasons: 1,
    ratings: {
      plot: 8,
      acting: 7,
      cinematography: 6,
      soundtrack: 6,
      dialogue: 7,
      rewatch: 3,
    },
    reviewKey: "jimmySavileABritishHorrorStoryReview",
    link: "https://www.imdb.com/title/tt18950880/",
    favorite: false,
  },
  {
    title: "Hitler: The Rise of Evil",
    director: "Christian Duguay",
    descriptionKey: "hitlerTheRiseOfEvilDescription",
    coverImage: "/images/films/hitler-rise-of-evil.jpg",
    dateWatched: "2024-05-15",
    yearReleased: 2003,
    genreKey: "Drama",
    mediaType: "tv",
    seasons: 1,
    ratings: {
      plot: 8,
      acting: 8,
      cinematography: 7,
      soundtrack: 7,
      dialogue: 7,
      rewatch: 5,
    },
    reviewKey: "hitlerTheRiseOfEvilReview",
    link: "https://www.imdb.com/title/tt0346293/",
    favorite: false,
  },

  // ── SQUID GAME / KOREAN ────────────────────────────────────
  {
    title: "Squid Game",
    director: "Hwang Dong-hyuk",
    descriptionKey: "squidGameDescription",
    coverImage: "/images/films/squid-game.jpg",
    dateWatched: "2024-09-01",
    yearReleased: 2021,
    genreKey: "Thriller",
    mediaType: "tv",
    seasons: 2,
    ratings: {
      plot: 9,
      acting: 8,
      cinematography: 9,
      soundtrack: 8,
      dialogue: 7,
      rewatch: 7,
    },
    reviewKey: "squidGameReview",
    link: "https://www.imdb.com/title/tt10919420/",
    favorite: true,
  },

  // ── ACTION ─────────────────────────────────────────────────
  {
    title: "The Expendables",
    director: "Sylvester Stallone",
    descriptionKey: "theExpendablesDescription",
    coverImage: "/images/films/the-expendables.jpg",
    dateWatched: "2023-07-01",
    yearReleased: 2010,
    genreKey: "Action",
    mediaType: "film",
    ratings: {
      plot: 5,
      acting: 6,
      cinematography: 6,
      soundtrack: 6,
      dialogue: 5,
      rewatch: 6,
    },
    reviewKey: "theExpendablesReview",
    link: "https://www.imdb.com/title/tt1320253/",
    favorite: false,
  },
  {
    title: "The Expendables 2",
    director: "Simon West",
    descriptionKey: "theExpendables2Description",
    coverImage: "/images/films/the-expendables-2.jpg",
    dateWatched: "2023-07-05",
    yearReleased: 2012,
    genreKey: "Action",
    mediaType: "film",
    ratings: {
      plot: 5,
      acting: 6,
      cinematography: 6,
      soundtrack: 6,
      dialogue: 6,
      rewatch: 6,
    },
    reviewKey: "theExpendables2Review",
    link: "https://www.imdb.com/title/tt1764651/",
    favorite: false,
  },
  {
    title: "The Expendables 3",
    director: "Patrick Hughes",
    descriptionKey: "theExpendables3Description",
    coverImage: "/images/films/the-expendables-3.jpg",
    dateWatched: "2023-07-10",
    yearReleased: 2014,
    genreKey: "Action",
    mediaType: "film",
    ratings: {
      plot: 4,
      acting: 5,
      cinematography: 6,
      soundtrack: 5,
      dialogue: 5,
      rewatch: 4,
    },
    reviewKey: "theExpendables3Review",
    link: "https://www.imdb.com/title/tt2333784/",
    favorite: false,
  },
  {
    title: "Avengers: Endgame",
    director: "Anthony & Joe Russo",
    descriptionKey: "avengersEndgameDescription",
    coverImage: "/images/films/avengers-endgame.jpg",
    dateWatched: "2023-12-10",
    yearReleased: 2019,
    genreKey: "Action",
    mediaType: "film",
    ratings: {
      plot: 8,
      acting: 8,
      cinematography: 9,
      soundtrack: 9,
      dialogue: 7,
      rewatch: 8,
    },
    reviewKey: "avengersEndgameReview",
    link: "https://www.imdb.com/title/tt4154796/",
    favorite: true,
  },
  {
    title: "Angel Has Fallen",
    director: "Ric Roman Waugh",
    descriptionKey: "angelHasFallenDescription",
    coverImage: "/images/films/angel-has-fallen.jpg",
    dateWatched: "2024-01-05",
    yearReleased: 2019,
    genreKey: "Action",
    mediaType: "film",
    ratings: {
      plot: 6,
      acting: 7,
      cinematography: 7,
      soundtrack: 6,
      dialogue: 6,
      rewatch: 5,
    },
    reviewKey: "angelHasFallenReview",
    link: "https://www.imdb.com/title/tt6189022/",
    favorite: false,
  },
  {
    title: "London Has Fallen",
    director: "Babak Najafi",
    descriptionKey: "londonHasFallenDescription",
    coverImage: "/images/films/london-has-fallen.jpg",
    dateWatched: "2024-01-02",
    yearReleased: 2016,
    genreKey: "Action",
    mediaType: "film",
    ratings: {
      plot: 5,
      acting: 6,
      cinematography: 6,
      soundtrack: 5,
      dialogue: 5,
      rewatch: 5,
    },
    reviewKey: "londonHasFallenReview",
    link: "https://www.imdb.com/title/tt3300542/",
    favorite: false,
  },
  {
    title: "Jurassic World",
    director: "Colin Trevorrow",
    descriptionKey: "jurassicWorldDescription",
    coverImage: "/images/films/jurassic-world.jpg",
    dateWatched: "2023-12-28",
    yearReleased: 2015,
    genreKey: "Action",
    mediaType: "film",
    ratings: {
      plot: 7,
      acting: 7,
      cinematography: 8,
      soundtrack: 8,
      dialogue: 6,
      rewatch: 7,
    },
    reviewKey: "jurassicWorldReview",
    link: "https://www.imdb.com/title/tt0369610/",
    favorite: false,
  },
  {
    title: "Jurassic World: Fallen Kingdom",
    director: "J.A. Bayona",
    descriptionKey: "jurassicWorldFallenKingdomDescription",
    coverImage: "/images/films/jurassic-world-fallen-kingdom.jpg",
    dateWatched: "2024-01-12",
    yearReleased: 2018,
    genreKey: "Action",
    mediaType: "film",
    ratings: {
      plot: 5,
      acting: 6,
      cinematography: 8,
      soundtrack: 7,
      dialogue: 5,
      rewatch: 5,
    },
    reviewKey: "jurassicWorldFallenKingdomReview",
    link: "https://www.imdb.com/title/tt4881806/",
    favorite: false,
  },
  {
    title: "Homefront",
    director: "Gary Fleder",
    descriptionKey: "homefrontDescription",
    coverImage: "/images/films/homefront.jpg",
    dateWatched: "2023-11-15",
    yearReleased: 2013,
    genreKey: "Action",
    mediaType: "film",
    ratings: {
      plot: 6,
      acting: 7,
      cinematography: 6,
      soundtrack: 5,
      dialogue: 6,
      rewatch: 5,
    },
    reviewKey: "homefrontReview",
    link: "https://www.imdb.com/title/tt2312718/",
    favorite: false,
  },
  {
    title: "Spenser Confidential",
    director: "Peter Berg",
    descriptionKey: "spenserConfidentialDescription",
    coverImage: "/images/films/spenser-confidential.jpg",
    dateWatched: "2024-02-10",
    yearReleased: 2020,
    genreKey: "Action",
    mediaType: "film",
    ratings: {
      plot: 6,
      acting: 7,
      cinematography: 6,
      soundtrack: 6,
      dialogue: 7,
      rewatch: 5,
    },
    reviewKey: "spenserConfidentialReview",
    link: "https://www.imdb.com/title/tt8629748/",
    favorite: false,
  },
  {
    title: "Central Intelligence",
    director: "Rawson Marshall Thurber",
    descriptionKey: "centralIntelligenceDescription",
    coverImage: "/images/films/central-intelligence.jpg",
    dateWatched: "2024-06-10",
    yearReleased: 2016,
    genreKey: "Comedy",
    mediaType: "film",
    ratings: {
      plot: 6,
      acting: 7,
      cinematography: 6,
      soundtrack: 5,
      dialogue: 7,
      rewatch: 6,
    },
    reviewKey: "centralIntelligenceReview",
    link: "https://www.imdb.com/title/tt1489889/",
    favorite: false,
  },
  {
    title: "Vikings",
    director: "Michael Hirst",
    descriptionKey: "vikingsDescription",
    coverImage: "/images/films/vikings.jpg",
    dateWatched: "2024-09-20",
    yearReleased: 2013,
    genreKey: "Action",
    mediaType: "tv",
    seasons: 6,
    ratings: {
      plot: 8,
      acting: 8,
      cinematography: 8,
      soundtrack: 8,
      dialogue: 7,
      rewatch: 7,
    },
    reviewKey: "vikingsReview",
    link: "https://www.imdb.com/title/tt2306299/",
    favorite: false,
  },

  // ── COMEDY ─────────────────────────────────────────────────
  {
    title: "About a Boy",
    director: "Chris Weitz & Paul Weitz",
    descriptionKey: "aboutABoyDescription",
    coverImage: "/images/films/about-a-boy.jpg",
    dateWatched: "2024-08-12",
    yearReleased: 2002,
    genreKey: "Comedy",
    mediaType: "film",
    ratings: {
      plot: 7,
      acting: 8,
      cinematography: 6,
      soundtrack: 7,
      dialogue: 8,
      rewatch: 7,
    },
    reviewKey: "aboutABoyReview",
    link: "https://www.imdb.com/title/tt0276751/",
    favorite: false,
  },
  {
    title: "Peep Show",
    director: "Jesse Armstrong & Sam Bain",
    descriptionKey: "peepShowDescription",
    coverImage: "/images/films/peep-show.webp",
    dateWatched: "2024-10-01",
    yearReleased: 2003,
    genreKey: "Comedy",
    mediaType: "tv",
    seasons: 9,
    ratings: {
      plot: 7,
      acting: 9,
      cinematography: 5,
      soundtrack: 5,
      dialogue: 10,
      rewatch: 9,
    },
    reviewKey: "peepShowReview",
    link: "https://www.imdb.com/title/tt0387764/",
    favorite: true,
  },
  {
    title: "The Inbetweeners",
    director: "Damon Beesley & Iain Morris",
    descriptionKey: "theInbetweenersDescription",
    coverImage: "/images/films/the-inbetweeners.jpg",
    dateWatched: "2023-08-01",
    yearReleased: 2008,
    genreKey: "Comedy",
    mediaType: "tv",
    seasons: 3,
    ratings: {
      plot: 7,
      acting: 8,
      cinematography: 5,
      soundtrack: 5,
      dialogue: 10,
      rewatch: 9,
    },
    reviewKey: "theInbetweenersReview",
    link: "https://www.imdb.com/title/tt1220617/",
    favorite: true,
  },
  {
    title: "After Life",
    director: "Ricky Gervais",
    descriptionKey: "afterLifeDescription",
    coverImage: "/images/films/after-life.jpg",
    dateWatched: "2024-07-15",
    yearReleased: 2019,
    genreKey: "Comedy",
    mediaType: "tv",
    seasons: 3,
    ratings: {
      plot: 7,
      acting: 8,
      cinematography: 6,
      soundtrack: 7,
      dialogue: 8,
      rewatch: 7,
    },
    reviewKey: "afterLifeReview",
    link: "https://www.imdb.com/title/tt8398600/",
    favorite: false,
  },
  {
    title: "Derek",
    director: "Ricky Gervais",
    descriptionKey: "derekDescription",
    coverImage: "/images/films/derek.jpg",
    dateWatched: "2024-07-20",
    yearReleased: 2012,
    genreKey: "Comedy",
    mediaType: "tv",
    seasons: 2,
    ratings: {
      plot: 7,
      acting: 8,
      cinematography: 5,
      soundtrack: 6,
      dialogue: 7,
      rewatch: 6,
    },
    reviewKey: "derekReview",
    link: "https://www.imdb.com/title/tt2616280/",
    favorite: false,
  },
  {
    title: "The Office",
    director: "Ricky Gervais & Stephen Merchant",
    descriptionKey: "theOfficeDescription",
    coverImage: "/images/films/the-office.jpg",
    dateWatched: "2024-07-25",
    yearReleased: 2001,
    genreKey: "Comedy",
    mediaType: "tv",
    seasons: 2,
    ratings: {
      plot: 8,
      acting: 10,
      cinematography: 6,
      soundtrack: 6,
      dialogue: 10,
      rewatch: 9,
    },
    reviewKey: "theOfficeReview",
    link: "https://www.imdb.com/title/tt0290978/",
    favorite: true,
  },
  {
    title: "Bad Education",
    director: "Jack Whitehall & Freddy Syborn",
    descriptionKey: "badEducationDescription",
    coverImage: "/images/films/bad-education.jpg",
    dateWatched: "2024-06-25",
    yearReleased: 2012,
    genreKey: "Comedy",
    mediaType: "tv",
    seasons: 3,
    ratings: {
      plot: 6,
      acting: 7,
      cinematography: 5,
      soundtrack: 5,
      dialogue: 8,
      rewatch: 7,
    },
    reviewKey: "badEducationReview",
    link: "https://www.imdb.com/title/tt2337840/",
    favorite: false,
  },
  {
    title: "Orange Is the New Black",
    director: "Jenji Kohan",
    descriptionKey: "orangeIsTheNewBlackDescription",
    coverImage: "/images/films/orange-is-the-new-black.jpg",
    dateWatched: "2023-08-15",
    yearReleased: 2013,
    genreKey: "Drama",
    mediaType: "tv",
    seasons: 7,
    ratings: {
      plot: 7,
      acting: 8,
      cinematography: 6,
      soundtrack: 6,
      dialogue: 8,
      rewatch: 6,
    },
    reviewKey: "orangeIsTheNewBlackReview",
    link: "https://www.imdb.com/title/tt2372162/",
    favorite: false,
  },
  {
    title: "Brooklyn Nine-Nine",
    director: "Dan Goor & Michael Schur",
    descriptionKey: "brooklynNinenineDescription",
    coverImage: "/images/films/brooklyn-nine-nine.jpg",
    dateWatched: "2024-08-01",
    yearReleased: 2013,
    genreKey: "Comedy",
    mediaType: "tv",
    seasons: 8,
    ratings: {
      plot: 7,
      acting: 8,
      cinematography: 6,
      soundtrack: 6,
      dialogue: 9,
      rewatch: 8,
    },
    reviewKey: "brooklynNinenineReview",
    link: "https://www.imdb.com/title/tt2467372/",
    favorite: true,
  },
  {
    title: "Sex Education",
    director: "Laurie Nunn",
    descriptionKey: "sexEducationDescription",
    coverImage: "/images/films/sex-education.jpg",
    dateWatched: "2024-09-10",
    yearReleased: 2019,
    genreKey: "Comedy",
    mediaType: "tv",
    seasons: 4,
    ratings: {
      plot: 7,
      acting: 8,
      cinematography: 7,
      soundtrack: 8,
      dialogue: 8,
      rewatch: 7,
    },
    reviewKey: "sexEducationReview",
    link: "https://www.imdb.com/title/tt7767422/",
    favorite: false,
  },
  {
    title: "This Country",
    director: "Daisy May Cooper & Charlie Cooper",
    descriptionKey: "thisCountryDescription",
    coverImage: "/images/films/this-country.jpg",
    dateWatched: "2024-09-25",
    yearReleased: 2017,
    genreKey: "Comedy",
    mediaType: "tv",
    seasons: 3,
    ratings: {
      plot: 7,
      acting: 9,
      cinematography: 5,
      soundtrack: 5,
      dialogue: 9,
      rewatch: 8,
    },
    reviewKey: "thisCountryReview",
    link: "https://www.imdb.com/title/tt6453980/",
    favorite: true,
  },
  {
    title: "Motherland",
    director: "Sharon Horgan & Holly Walsh & Helen Linehan",
    descriptionKey: "motherlandDescription",
    coverImage: "/images/films/motherland.jpg",
    dateWatched: "2024-10-05",
    yearReleased: 2016,
    genreKey: "Comedy",
    mediaType: "tv",
    seasons: 3,
    ratings: {
      plot: 7,
      acting: 8,
      cinematography: 5,
      soundtrack: 5,
      dialogue: 9,
      rewatch: 7,
    },
    reviewKey: "motherlandReview",
    link: "https://www.imdb.com/title/tt6286712/",
    favorite: false,
  },
  {
    title: "Friday Night Dinner",
    director: "Robert Popper",
    descriptionKey: "fridayNightDinnerDescription",
    coverImage: "/images/films/friday-night-dinner.jpg",
    dateWatched: "2024-10-10",
    yearReleased: 2011,
    genreKey: "Comedy",
    mediaType: "tv",
    seasons: 6,
    ratings: {
      plot: 6,
      acting: 8,
      cinematography: 5,
      soundtrack: 5,
      dialogue: 9,
      rewatch: 9,
    },
    reviewKey: "fridayNightDinnerReview",
    link: "https://www.imdb.com/title/tt1844923/",
    favorite: true,
  },
  {
    title: "Benidorm",
    director: "Derren Litten",
    descriptionKey: "benidormDescription",
    coverImage: "/images/films/benidorm.jpg",
    dateWatched: "2024-10-15",
    yearReleased: 2007,
    genreKey: "Comedy",
    mediaType: "tv",
    seasons: 10,
    ratings: {
      plot: 5,
      acting: 7,
      cinematography: 5,
      soundtrack: 4,
      dialogue: 7,
      rewatch: 6,
    },
    reviewKey: "benidormReview",
    link: "https://www.imdb.com/title/tt0840196/",
    favorite: false,
  },
  {
    title: "Haters Back Off",
    director: "Colleen Ballinger & Christopher Ballinger",
    descriptionKey: "hatersBackOffDescription",
    coverImage: "/images/films/haters-back-off.jpg",
    dateWatched: "2024-06-30",
    yearReleased: 2016,
    genreKey: "Comedy",
    mediaType: "tv",
    seasons: 2,
    ratings: {
      plot: 5,
      acting: 6,
      cinematography: 5,
      soundtrack: 4,
      dialogue: 6,
      rewatch: 4,
    },
    reviewKey: "hatersBackOffReview",
    link: "https://www.imdb.com/title/tt5765670/",
    favorite: false,
  },
  {
    title: "The Job Lot",
    director: "Claire Downes & Ian Jarvis & Stuart Lane",
    descriptionKey: "theJobLotDescription",
    coverImage: "/images/films/the-job-lot.jpg",
    dateWatched: "2024-10-20",
    yearReleased: 2013,
    genreKey: "Comedy",
    mediaType: "tv",
    seasons: 3,
    ratings: {
      plot: 6,
      acting: 7,
      cinematography: 5,
      soundtrack: 5,
      dialogue: 7,
      rewatch: 5,
    },
    reviewKey: "theJobLotReview",
    link: "https://www.imdb.com/title/tt2733824/",
    favorite: false,
  },
  {
    title: "Gavin & Stacey",
    director: "James Corden & Ruth Jones",
    descriptionKey: "gavinStaceyDescription",
    coverImage: "/images/films/gavin-and-stacey.jpg",
    dateWatched: "2024-11-01",
    yearReleased: 2007,
    genreKey: "Comedy",
    mediaType: "tv",
    seasons: 3,
    ratings: {
      plot: 7,
      acting: 8,
      cinematography: 5,
      soundtrack: 6,
      dialogue: 9,
      rewatch: 8,
    },
    reviewKey: "gavinStaceyReview",
    link: "https://www.imdb.com/title/tt1092026/",
    favorite: true,
  },
  {
    title: "Outnumbered",
    director: "Andy Hamilton & Guy Jenkin",
    descriptionKey: "outnumberedDescription",
    coverImage: "/images/films/outnumbered.jpg",
    dateWatched: "2024-10-25",
    yearReleased: 2007,
    genreKey: "Comedy",
    mediaType: "tv",
    seasons: 5,
    ratings: {
      plot: 7,
      acting: 8,
      cinematography: 5,
      soundtrack: 5,
      dialogue: 9,
      rewatch: 7,
    },
    reviewKey: "outnumberedReview",
    link: "https://www.imdb.com/title/tt1086191/",
    favorite: false,
  },
  {
    title: "Fresh Meat",
    director: "Jesse Armstrong & Sam Bain",
    descriptionKey: "freshMeatDescription",
    coverImage: "/images/films/fresh-meat.jpg",
    dateWatched: "2024-11-05",
    yearReleased: 2011,
    genreKey: "Comedy",
    mediaType: "tv",
    seasons: 4,
    ratings: {
      plot: 7,
      acting: 8,
      cinematography: 6,
      soundtrack: 6,
      dialogue: 9,
      rewatch: 7,
    },
    reviewKey: "freshMeatReview",
    link: "https://www.imdb.com/title/tt2058303/",
    favorite: false,
  },
  {
    title: "The End of the F***ing World",
    director: "Jonathan Entwistle",
    descriptionKey: "theEndOfTheFingWorldDescription",
    coverImage: "/images/films/end-of-the-world.jpg",
    dateWatched: "2024-11-10",
    yearReleased: 2017,
    genreKey: "Drama",
    mediaType: "tv",
    seasons: 2,
    ratings: {
      plot: 8,
      acting: 8,
      cinematography: 8,
      soundtrack: 8,
      dialogue: 8,
      rewatch: 7,
    },
    reviewKey: "theEndOfTheFingWorldReview",
    link: "https://www.imdb.com/title/tt6257970/",
    favorite: false,
  },
  {
    title: "Unbreakable Kimmy Schmidt",
    director: "Tina Fey & Robert Carlock",
    descriptionKey: "unbreakableKimmySchmidtDescription",
    coverImage: "/images/films/unbreakable-kimmy-schmidt.jpg",
    dateWatched: "2024-08-20",
    yearReleased: 2015,
    genreKey: "Comedy",
    mediaType: "tv",
    seasons: 4,
    ratings: {
      plot: 7,
      acting: 8,
      cinematography: 6,
      soundtrack: 6,
      dialogue: 8,
      rewatch: 6,
    },
    reviewKey: "unbreakableKimmySchmidtReview",
    link: "https://www.imdb.com/title/tt3339966/",
    favorite: false,
  },
  {
    title: "Citizen Khan",
    director: "Adil Ray",
    descriptionKey: "citizenKhanDescription",
    coverImage: "/images/films/citizen-khan.jpg",
    dateWatched: "2024-09-05",
    yearReleased: 2012,
    genreKey: "Comedy",
    mediaType: "tv",
    seasons: 5,
    ratings: {
      plot: 6,
      acting: 7,
      cinematography: 5,
      soundtrack: 5,
      dialogue: 7,
      rewatch: 5,
    },
    reviewKey: "citizenKhanReview",
    link: "https://www.imdb.com/title/tt2234055/",
    favorite: false,
  },
  {
    title: "Step Brothers",
    director: "Adam McKay",
    descriptionKey: "stepBrothersDescription",
    coverImage: "/images/films/step-brothers.jpg",
    dateWatched: "2023-06-01",
    yearReleased: 2008,
    genreKey: "Comedy",
    mediaType: "film",
    ratings: {
      plot: 6,
      acting: 8,
      cinematography: 5,
      soundtrack: 6,
      dialogue: 9,
      rewatch: 9,
    },
    reviewKey: "stepBrothersReview",
    link: "https://www.imdb.com/title/tt0838283/",
    favorite: true,
  },
  {
    title: "Daddy's Home",
    director: "Sean Anders",
    descriptionKey: "daddysHomeDescription",
    coverImage: "/images/films/daddys-home.jpg",
    dateWatched: "2023-06-05",
    yearReleased: 2015,
    genreKey: "Comedy",
    mediaType: "film",
    ratings: {
      plot: 5,
      acting: 7,
      cinematography: 5,
      soundtrack: 5,
      dialogue: 7,
      rewatch: 6,
    },
    reviewKey: "daddysHomeReview",
    link: "https://www.imdb.com/title/tt1528854/",
    favorite: false,
  },
  {
    title: "Daddy's Home 2",
    director: "Sean Anders",
    descriptionKey: "daddysHome2Description",
    coverImage: "/images/films/daddys-home-2.jpg",
    dateWatched: "2023-06-08",
    yearReleased: 2017,
    genreKey: "Comedy",
    mediaType: "film",
    ratings: {
      plot: 5,
      acting: 7,
      cinematography: 5,
      soundtrack: 5,
      dialogue: 6,
      rewatch: 5,
    },
    reviewKey: "daddysHome2Review",
    link: "https://www.imdb.com/title/tt5658412/",
    favorite: false,
  },
  {
    title: "21 Jump Street",
    director: "Phil Lord & Christopher Miller",
    descriptionKey: "21JumpStreetDescription",
    coverImage: "/images/films/21-jump-street.jpg",
    dateWatched: "2023-08-10",
    yearReleased: 2012,
    genreKey: "Comedy",
    mediaType: "film",
    ratings: {
      plot: 7,
      acting: 8,
      cinematography: 6,
      soundtrack: 6,
      dialogue: 9,
      rewatch: 8,
    },
    reviewKey: "21JumpStreetReview",
    link: "https://www.imdb.com/title/tt1232829/",
    favorite: false,
  },
  {
    title: "22 Jump Street",
    director: "Phil Lord & Christopher Miller",
    descriptionKey: "22JumpStreetDescription",
    coverImage: "/images/films/22-jump-street.jpg",
    dateWatched: "2023-08-12",
    yearReleased: 2014,
    genreKey: "Comedy",
    mediaType: "film",
    ratings: {
      plot: 7,
      acting: 8,
      cinematography: 6,
      soundtrack: 6,
      dialogue: 9,
      rewatch: 8,
    },
    reviewKey: "22JumpStreetReview",
    link: "https://www.imdb.com/title/tt2294449/",
    favorite: false,
  },
  {
    title: "Murder Mystery",
    director: "Kyle Newacheck",
    descriptionKey: "murderMysteryDescription",
    coverImage: "/images/films/murder-mystery.jpg",
    dateWatched: "2024-02-05",
    yearReleased: 2019,
    genreKey: "Comedy",
    mediaType: "film",
    ratings: {
      plot: 6,
      acting: 7,
      cinematography: 7,
      soundtrack: 5,
      dialogue: 7,
      rewatch: 6,
    },
    reviewKey: "murderMysteryReview",
    link: "https://www.imdb.com/title/tt1618434/",
    favorite: false,
  },
  {
    title: "Murder Mystery 2",
    director: "Jeremy Garelick",
    descriptionKey: "murderMystery2Description",
    coverImage: "/images/films/murder-mystery-2.jpg",
    dateWatched: "2024-02-08",
    yearReleased: 2023,
    genreKey: "Comedy",
    mediaType: "film",
    ratings: {
      plot: 5,
      acting: 7,
      cinematography: 7,
      soundtrack: 5,
      dialogue: 6,
      rewatch: 5,
    },
    reviewKey: "murderMystery2Review",
    link: "https://www.imdb.com/title/tt15255288/",
    favorite: false,
  },
  {
    title: "The Wrong Missy",
    director: "Tyler Spindel",
    descriptionKey: "theWrongMissyDescription",
    coverImage: "/images/films/the-wrong-missy.jpg",
    dateWatched: "2024-03-01",
    yearReleased: 2020,
    genreKey: "Comedy",
    mediaType: "film",
    ratings: {
      plot: 5,
      acting: 7,
      cinematography: 5,
      soundtrack: 4,
      dialogue: 6,
      rewatch: 5,
    },
    reviewKey: "theWrongMissyReview",
    link: "https://www.imdb.com/title/tt9619798/",
    favorite: false,
  },
  {
    title: "That's My Boy",
    director: "Sean Anders",
    descriptionKey: "thatsMyBoyDescription",
    coverImage: "/images/films/thats-my-boy.jpg",
    dateWatched: "2023-07-20",
    yearReleased: 2012,
    genreKey: "Comedy",
    mediaType: "film",
    ratings: {
      plot: 5,
      acting: 6,
      cinematography: 5,
      soundtrack: 5,
      dialogue: 6,
      rewatch: 5,
    },
    reviewKey: "thatsMyBoyReview",
    link: "https://www.imdb.com/title/tt1232200/",
    favorite: false,
  },
  {
    title: "Grown Ups",
    director: "Dennis Dugan",
    descriptionKey: "grownUpsDescription",
    coverImage: "/images/films/grown-ups.jpg",
    dateWatched: "2023-07-25",
    yearReleased: 2010,
    genreKey: "Comedy",
    mediaType: "film",
    ratings: {
      plot: 5,
      acting: 6,
      cinematography: 5,
      soundtrack: 5,
      dialogue: 6,
      rewatch: 6,
    },
    reviewKey: "grownUpsReview",
    link: "https://www.imdb.com/title/tt1375670/",
    favorite: false,
  },
  {
    title: "Grown Ups 2",
    director: "Dennis Dugan",
    descriptionKey: "grownUps2Description",
    coverImage: "/images/films/grown-ups-2.jpg",
    dateWatched: "2023-07-28",
    yearReleased: 2013,
    genreKey: "Comedy",
    mediaType: "film",
    ratings: {
      plot: 4,
      acting: 6,
      cinematography: 5,
      soundtrack: 4,
      dialogue: 5,
      rewatch: 4,
    },
    reviewKey: "grownUps2Review",
    link: "https://www.imdb.com/title/tt2191701/",
    favorite: false,
  },
  {
    title: "Anchorman: The Legend of Ron Burgundy",
    director: "Adam McKay",
    descriptionKey: "anchormanTheLegendOfRonBurgundyDescription",
    coverImage: "/images/films/anchorman.jpg",
    dateWatched: "2023-05-15",
    yearReleased: 2004,
    genreKey: "Comedy",
    mediaType: "film",
    ratings: {
      plot: 6,
      acting: 9,
      cinematography: 6,
      soundtrack: 7,
      dialogue: 10,
      rewatch: 9,
    },
    reviewKey: "anchormanTheLegendOfRonBurgundyReview",
    link: "https://www.imdb.com/title/tt0357413/",
    favorite: true,
  },
  {
    title: "Anchorman 2: The Legend Continues",
    director: "Adam McKay",
    descriptionKey: "anchorman2TheLegendContinuesDescription",
    coverImage: "/images/films/anchorman-2.jpg",
    dateWatched: "2023-05-18",
    yearReleased: 2013,
    genreKey: "Comedy",
    mediaType: "film",
    ratings: {
      plot: 5,
      acting: 8,
      cinematography: 6,
      soundtrack: 6,
      dialogue: 7,
      rewatch: 6,
    },
    reviewKey: "anchorman2TheLegendContinuesReview",
    link: "https://www.imdb.com/title/tt1229340/",
    favorite: false,
  },
  {
    title: "Get Hard",
    director: "Etan Cohen",
    descriptionKey: "getHardDescription",
    coverImage: "/images/films/get-hard.jpg",
    dateWatched: "2023-08-05",
    yearReleased: 2015,
    genreKey: "Comedy",
    mediaType: "film",
    ratings: {
      plot: 5,
      acting: 7,
      cinematography: 5,
      soundtrack: 5,
      dialogue: 7,
      rewatch: 5,
    },
    reviewKey: "getHardReview",
    link: "https://www.imdb.com/title/tt2561572/",
    favorite: false,
  },
  {
    title: "Identity Thief",
    director: "Seth Gordon",
    descriptionKey: "identityThiefDescription",
    coverImage: "/images/films/identity-thief.jpg",
    dateWatched: "2024-03-10",
    yearReleased: 2013,
    genreKey: "Comedy",
    mediaType: "film",
    ratings: {
      plot: 5,
      acting: 7,
      cinematography: 5,
      soundtrack: 5,
      dialogue: 6,
      rewatch: 5,
    },
    reviewKey: "identityThiefReview",
    link: "https://www.imdb.com/title/tt2024432/",
    favorite: false,
  },
  {
    title: "Dodgeball: A True Underdog Story",
    director: "Rawson Marshall Thurber",
    descriptionKey: "dodgeballATrueUnderdogStoryDescription",
    coverImage: "/images/films/dodgeball.jpg",
    dateWatched: "2023-06-15",
    yearReleased: 2004,
    genreKey: "Comedy",
    mediaType: "film",
    ratings: {
      plot: 6,
      acting: 8,
      cinematography: 5,
      soundtrack: 6,
      dialogue: 9,
      rewatch: 8,
    },
    reviewKey: "dodgeballATrueUnderdogStoryReview",
    link: "https://www.imdb.com/title/tt0364725/",
    favorite: false,
  },
  {
    title: "Norbit",
    director: "Brian Robbins",
    descriptionKey: "norbitDescription",
    coverImage: "/images/films/norbit.jpg",
    dateWatched: "2023-09-10",
    yearReleased: 2007,
    genreKey: "Comedy",
    mediaType: "film",
    ratings: {
      plot: 4,
      acting: 6,
      cinematography: 5,
      soundtrack: 4,
      dialogue: 5,
      rewatch: 4,
    },
    reviewKey: "norbitReview",
    link: "https://www.imdb.com/title/tt0477051/",
    favorite: false,
  },
  {
    title: "Here Comes the Boom",
    director: "Frank Coraci",
    descriptionKey: "hereComesTheBoomDescription",
    coverImage: "/images/films/here-comes-the-boom.jpg",
    dateWatched: "2023-09-15",
    yearReleased: 2012,
    genreKey: "Comedy",
    mediaType: "film",
    ratings: {
      plot: 6,
      acting: 7,
      cinematography: 6,
      soundtrack: 6,
      dialogue: 6,
      rewatch: 6,
    },
    reviewKey: "hereComesTheBoomReview",
    link: "https://www.imdb.com/title/tt1648179/",
    favorite: false,
  },
  {
    title: "Chef",
    director: "Jon Favreau",
    descriptionKey: "chefDescription",
    coverImage: "/images/films/chef.jpg",
    dateWatched: "2024-04-15",
    yearReleased: 2014,
    genreKey: "Comedy",
    mediaType: "film",
    ratings: {
      plot: 7,
      acting: 8,
      cinematography: 7,
      soundtrack: 8,
      dialogue: 7,
      rewatch: 8,
    },
    reviewKey: "chefReview",
    link: "https://www.imdb.com/title/tt2883512/",
    favorite: false,
  },
  {
    title: "The Internship",
    director: "Shawn Levy",
    descriptionKey: "theInternshipDescription",
    coverImage: "/images/films/the-internship.jpg",
    dateWatched: "2024-04-18",
    yearReleased: 2013,
    genreKey: "Comedy",
    mediaType: "film",
    ratings: {
      plot: 5,
      acting: 7,
      cinematography: 6,
      soundtrack: 5,
      dialogue: 7,
      rewatch: 5,
    },
    reviewKey: "theInternshipReview",
    link: "https://www.imdb.com/title/tt2234155/",
    favorite: false,
  },
  {
    title: "Dirty Grandpa",
    director: "Dan Mazer",
    descriptionKey: "dirtyGrandpaDescription",
    coverImage: "/images/films/dirty-grandpa.jpg",
    dateWatched: "2024-04-22",
    yearReleased: 2016,
    genreKey: "Comedy",
    mediaType: "film",
    ratings: {
      plot: 4,
      acting: 6,
      cinematography: 5,
      soundtrack: 4,
      dialogue: 5,
      rewatch: 4,
    },
    reviewKey: "dirtyGrandpaReview",
    link: "https://www.imdb.com/title/tt1860213/",
    favorite: false,
  },
  {
    title: "Paul Blart: Mall Cop",
    director: "Steve Carr",
    descriptionKey: "paulBlartMallCopDescription",
    coverImage: "/images/films/paul-blart.jpg",
    dateWatched: "2023-10-01",
    yearReleased: 2009,
    genreKey: "Comedy",
    mediaType: "film",
    ratings: {
      plot: 5,
      acting: 6,
      cinematography: 5,
      soundtrack: 5,
      dialogue: 6,
      rewatch: 5,
    },
    reviewKey: "paulBlartMallCopReview",
    link: "https://www.imdb.com/title/tt1114740/",
    favorite: false,
  },
  {
    title: "Paul Blart: Mall Cop 2",
    director: "Andy Fickman",
    descriptionKey: "paulBlartMallCop2Description",
    coverImage: "/images/films/paul-blart-2.jpg",
    dateWatched: "2023-10-03",
    yearReleased: 2015,
    genreKey: "Comedy",
    mediaType: "film",
    ratings: {
      plot: 3,
      acting: 5,
      cinematography: 5,
      soundtrack: 4,
      dialogue: 4,
      rewatch: 3,
    },
    reviewKey: "paulBlartMallCop2Review",
    link: "https://www.imdb.com/title/tt3450650/",
    favorite: false,
  },

  // ── ANIMATION ──────────────────────────────────────────────
  {
    title: "Big Hero 6",
    director: "Don Hall & Chris Williams",
    descriptionKey: "bigHero6Description",
    coverImage: "/images/films/big-hero-6.jpeg",
    dateWatched: "2023-12-25",
    yearReleased: 2014,
    genreKey: "Animation",
    mediaType: "film",
    ratings: {
      plot: 7,
      acting: 7,
      cinematography: 8,
      soundtrack: 7,
      dialogue: 7,
      rewatch: 8,
    },
    reviewKey: "bigHero6Review",
    link: "https://www.imdb.com/title/tt2245084/",
    favorite: false,
  },
  {
    title: "Kung Fu Panda",
    director: "Mark Osborne & John Stevenson",
    descriptionKey: "kungFuPandaDescription",
    coverImage: "/images/films/kung-fu-panda.jpg",
    dateWatched: "2023-11-20",
    yearReleased: 2008,
    genreKey: "Animation",
    mediaType: "film",
    ratings: {
      plot: 7,
      acting: 8,
      cinematography: 8,
      soundtrack: 8,
      dialogue: 7,
      rewatch: 8,
    },
    reviewKey: "kungFuPandaReview",
    link: "https://www.imdb.com/title/tt0441773/",
    favorite: false,
  },
  {
    title: "Kung Fu Panda 2",
    director: "Jennifer Yuh Nelson",
    descriptionKey: "kungFuPanda2Description",
    coverImage: "/images/films/kung-fu-panda-2.jpg",
    dateWatched: "2023-11-22",
    yearReleased: 2011,
    genreKey: "Animation",
    mediaType: "film",
    ratings: {
      plot: 8,
      acting: 8,
      cinematography: 9,
      soundtrack: 8,
      dialogue: 7,
      rewatch: 7,
    },
    reviewKey: "kungFuPanda2Review",
    link: "https://www.imdb.com/title/tt1302011/",
    favorite: false,
  },
  {
    title: "Kung Fu Panda 3",
    director: "Alessandro Carloni & Jennifer Yuh Nelson",
    descriptionKey: "kungFuPanda3Description",
    coverImage: "/images/films/kung-fu-panda-3.jpg",
    dateWatched: "2023-11-24",
    yearReleased: 2016,
    genreKey: "Animation",
    mediaType: "film",
    ratings: {
      plot: 7,
      acting: 7,
      cinematography: 8,
      soundtrack: 7,
      dialogue: 7,
      rewatch: 7,
    },
    reviewKey: "kungFuPanda3Review",
    link: "https://www.imdb.com/title/tt2267968/",
    favorite: false,
  },
  {
    title: "The Lego Movie",
    director: "Phil Lord & Christopher Miller",
    descriptionKey: "theLegoMovieDescription",
    coverImage: "/images/films/the-lego-movie.jpg",
    dateWatched: "2023-12-20",
    yearReleased: 2014,
    genreKey: "Animation",
    mediaType: "film",
    ratings: {
      plot: 8,
      acting: 8,
      cinematography: 9,
      soundtrack: 8,
      dialogue: 9,
      rewatch: 8,
    },
    reviewKey: "theLegoMovieReview",
    link: "https://www.imdb.com/title/tt1490017/",
    favorite: true,
  },
  {
    title: "Bee Movie",
    director: "Simon J. Smith & Steve Hickner",
    descriptionKey: "beeMovieDescription",
    coverImage: "/images/films/bee-movie.jpg",
    dateWatched: "2023-10-25",
    yearReleased: 2007,
    genreKey: "Animation",
    mediaType: "film",
    ratings: {
      plot: 5,
      acting: 6,
      cinematography: 6,
      soundtrack: 5,
      dialogue: 7,
      rewatch: 5,
    },
    reviewKey: "beeMovieReview",
    link: "https://www.imdb.com/title/tt0389790/",
    favorite: false,
  },
];
