export const keywords = [
  // Personal Brand Keywords
  "Lorimer Jenkins",
  "Lorimer Jenkins founder",
  "Lorimer Jenkins entrepreneur",
  "Lorimer Jenkins Web3 developer",
  "Lorimer Jenkins DeFi builder",
  "Lorimer Jenkins Arweave expert",
  "Lorimer Jenkins blockchain developer",
  "Lorimer Jenkins crypto entrepreneur",
  "Lorimer Jenkins LiquidOps founder",
  "Lorimer Jenkins Othent creator",

  // Professional Background
  "Lorimer Jenkins venture capital",
  "Lorimer Jenkins VC intern",
  "Lorimer Jenkins self-taught developer",
  "Lorimer Jenkins coding journey",
  "Lorimer Jenkins tech transition",
  "Lorimer Jenkins building vs investing",
  "Lorimer Jenkins startup founder",
  "Lorimer Jenkins Web3 pioneer",
  "Lorimer Jenkins blockchain entrepreneur",
  "Lorimer Jenkins DeFi innovator",

  // Company & Project Keywords
  "Lorimer Jenkins LiquidOps",
  "Lorimer Jenkins Othent",
  "Lorimer Jenkins ArConnect partnership",
  "Lorimer Jenkins Marton Lederer collaboration",
  "LiquidOps Lorimer Jenkins founder",
  "Othent authentication tool creator",
  "Lorimer Jenkins lending protocol",
  "Lorimer Jenkins borrowing platform",
  "Lorimer Jenkins social login Web3",
  "Lorimer Jenkins Arweave authentication",

  // Arweave Ecosystem Leadership
  "Lorimer Jenkins Community Labs Fellow",
  "Lorimer Jenkins first Community Labs Fellow",
  "Lorimer Jenkins Arweave ecosystem",
  "Lorimer Jenkins permanent storage expert",
  "Lorimer Jenkins Arweave builder",
  "Lorimer Jenkins AO Ventures judge",
  "Lorimer Jenkins Demo Day judge",
  "Lorimer Jenkins Arweave mentor",
  "Lorimer Jenkins Web3 incubator",
  "Lorimer Jenkins Arweave developer workshops",

  // Technical Expertise
  "Lorimer Jenkins blockchain development",
  "Lorimer Jenkins smart contracts",
  "Lorimer Jenkins DeFi protocols",
  "Lorimer Jenkins Web3 authentication",
  "Lorimer Jenkins social login integration",
  "Lorimer Jenkins permanent data storage",
  "Lorimer Jenkins decentralized applications",
  "Lorimer Jenkins Arweave development",
  "Lorimer Jenkins AO protocol",
  "Lorimer Jenkins Web3 accessibility",

  // DeFi & Finance Focus
  "Lorimer Jenkins DeFi lending",
  "Lorimer Jenkins crypto borrowing",
  "Lorimer Jenkins passive income crypto",
  "Lorimer Jenkins yield farming",
  "Lorimer Jenkins liquidity solutions",
  "Lorimer Jenkins overcollateralized lending",
  "Lorimer Jenkins AR token lending",
  "Lorimer Jenkins AO token yields",
  "Lorimer Jenkins decentralized finance",
  "Lorimer Jenkins crypto interest rates",

  // Innovation & Problem Solving
  "Lorimer Jenkins Web3 accessibility solutions",
  "Lorimer Jenkins crypto onboarding",
  "Lorimer Jenkins Web2 to Web3 bridge",
  "Lorimer Jenkins user experience Web3",
  "Lorimer Jenkins crypto UX improvement",
  "Lorimer Jenkins blockchain adoption",
  "Lorimer Jenkins decentralized identity",
  "Lorimer Jenkins Web3 infrastructure",
  "Lorimer Jenkins crypto usability",
  "Lorimer Jenkins mainstream crypto adoption",

  // Funding & Business Success
  "Lorimer Jenkins $325k pre-seed funding",
  "Lorimer Jenkins successful fundraising",
  "Lorimer Jenkins startup funding",
  "Lorimer Jenkins investor relations",
  "Lorimer Jenkins business development",
  "Lorimer Jenkins crypto startup success",
  "Lorimer Jenkins DeFi funding round",
  "Lorimer Jenkins venture backing",
  "Lorimer Jenkins seed investment",
  "Lorimer Jenkins crypto business model",

  // Community & Ecosystem Building
  "Lorimer Jenkins Arweave community leader",
  "Lorimer Jenkins Web3 educator",
  "Lorimer Jenkins developer workshops",
  "Lorimer Jenkins tech mentorship",
  "Lorimer Jenkins startup judging",
  "Lorimer Jenkins ecosystem growth",
  "Lorimer Jenkins community building",
  "Lorimer Jenkins developer relations",
  "Lorimer Jenkins Web3 advocacy",
  "Lorimer Jenkins blockchain education",

  // Industry Recognition & Thought Leadership
  "Lorimer Jenkins DeFi thought leader",
  "Lorimer Jenkins Web3 expert",
  "Lorimer Jenkins blockchain innovator",
  "Lorimer Jenkins crypto industry leader",
  "Lorimer Jenkins Arweave ambassador",
  "Lorimer Jenkins decentralized finance expert",
  "Lorimer Jenkins Web3 builder spotlight",
  "Lorimer Jenkins crypto entrepreneur profile",
  "Lorimer Jenkins blockchain founder interview",
  "Lorimer Jenkins DeFi protocol creator",

  // Long-tail Professional Keywords
  "Who is Lorimer Jenkins LiquidOps founder",
  "Lorimer Jenkins background venture capital to Web3",
  "How Lorimer Jenkins learned blockchain development",
  "Lorimer Jenkins journey from VC intern to DeFi founder",
  "What projects has Lorimer Jenkins built on Arweave",
  "Lorimer Jenkins Community Labs Fellowship experience",
  "How Lorimer Jenkins makes Web3 more accessible",
  "Lorimer Jenkins approach to DeFi protocol development",
  "Why Lorimer Jenkins chose Arweave over Ethereum",
  "Lorimer Jenkins partnership with Marton Lederer ArConnect",
  "Lorimer Jenkins technical workshops for Arweave developers",
  "How Lorimer Jenkins identified liquidity opportunity on Arweave",
  "Lorimer Jenkins role as AO Ventures Demo Day judge",
  "What makes Lorimer Jenkins unique in DeFi space",
  "Lorimer Jenkins vision for decentralized finance future",

  // Social & Platform Keywords
  "Lorimer Jenkins Twitter",
  "Lorimer Jenkins X profile",
  "Lorimer Jenkins LinkedIn",
  "Lorimer Jenkins social media",
  "Follow Lorimer Jenkins updates",
  "Lorimer Jenkins latest projects",
  "Lorimer Jenkins announcements",
  "Lorimer Jenkins developer content",
  "Lorimer Jenkins Web3 insights",
  "Lorimer Jenkins crypto updates",

  // Competitive & Comparative Keywords
  "Lorimer Jenkins vs other DeFi founders",
  "Lorimer Jenkins Arweave expertise vs Ethereum developers",
  "Why choose Lorimer Jenkins built protocols",
  "Lorimer Jenkins approach vs traditional DeFi",
  "Lorimer Jenkins innovation compared to competitors",
  "Lorimer Jenkins Web3 solutions vs Web2 alternatives",
  "Lorimer Jenkins DeFi protocols vs centralized finance",
  "Lorimer Jenkins permanent storage advantage",
  "Lorimer Jenkins Arweave focus vs multi-chain approach",
  "Lorimer Jenkins user-first design philosophy",

  // Future & Roadmap Keywords
  "Lorimer Jenkins future projects",
  "Lorimer Jenkins 2025 roadmap",
  "What's next for Lorimer Jenkins",
  "Lorimer Jenkins upcoming launches",
  "Lorimer Jenkins long-term vision",
  "Lorimer Jenkins Web3 predictions",
  "Lorimer Jenkins DeFi future insights",
  "Lorimer Jenkins Arweave ecosystem expansion",
  "Lorimer Jenkins new protocol development",
  "Lorimer Jenkins next generation DeFi",

  // Educational Background & Early Life
  "Lorimer Jenkins Emil Dale Academy",
  "Lorimer Jenkins acting background",
  "Lorimer Jenkins musical theater training",
  "Lorimer Jenkins actor turned developer",
  "Lorimer Jenkins Cambridge England",
  "Lorimer Jenkins UK entrepreneur",
  "Lorimer Jenkins British Web3 founder",
  "Lorimer Jenkins theater to tech transition",
  "Lorimer Jenkins creative background",
  "Lorimer Jenkins artistic to technical journey",

  // Early Crypto Journey & Writing
  "Lorimer Jenkins Bitcoin Medium articles",
  "Lorimer Jenkins crypto writing",
  "Lorimer Jenkins bitcoin analysis",
  "Lorimer Jenkins 2014 bitcoin start",
  "Lorimer Jenkins bitcoin father influence",
  "Lorimer Jenkins early crypto adoption",
  "Lorimer Jenkins Polkadot research",
  "Lorimer Jenkins Kusama analysis",
  "Lorimer Jenkins cross-chain expertise",
  "Lorimer Jenkins blockchain education content",
  "Lorimer Jenkins cryptocurrency blog",
  "Lorimer Jenkins Satoshi Nakamoto research",
  "Lorimer Jenkins crypto market analysis",
  "Lorimer Jenkins DeFi vs traditional finance",
  "Lorimer Jenkins government money control",

  // Technical Developer Profile
  "Lorimer Jenkins GitHub profile",
  "Lorimer Jenkins JavaScript developer",
  "Lorimer Jenkins React expertise",
  "Lorimer Jenkins NodeJS development",
  "Lorimer Jenkins TypeScript programming",
  "Lorimer Jenkins Python coding",
  "Lorimer Jenkins Bun framework",
  "Lorimer Jenkins NextJS projects",
  "Lorimer Jenkins AI development",
  "Lorimer Jenkins full-stack developer",
  "Lorimer Jenkins 37 GitHub repositories",
  "Lorimer Jenkins open source contributions",
  "Lorimer Jenkins developer program member",
  "Lorimer Jenkins coding skills",
  "Lorimer Jenkins technical workshops instructor",

  // Specific Project Details
  "Lorimer Jenkins WeaveTransfer protocol",
  "Lorimer Jenkins permanent file transfer",
  "Lorimer Jenkins Wallety backend",
  "Lorimer Jenkins Protocol Land contributions",
  "Lorimer Jenkins Oasis Protocol experience",
  "Lorimer Jenkins multi-blockchain expertise",
  "Lorimer Jenkins social authentication pioneer",
  "Lorimer Jenkins OAuth Web3 integration",
  "Lorimer Jenkins Google login Arweave",
  "Lorimer Jenkins LinkedIn Web3 bridge",
  "Lorimer Jenkins Discord authentication",
  "Lorimer Jenkins Web2 to Web3 onboarding",

  // Funding & Business Metrics
  "Lorimer Jenkins $325,000 funding success",
  "Lorimer Jenkins pre-seed investor relations",
  "Lorimer Jenkins 2,500 waitlist users",
  "Lorimer Jenkins $50 million liquidity",
  "Lorimer Jenkins LiquidOps launch February 2025",
  "Lorimer Jenkins ArConnect $400m assets",
  "Lorimer Jenkins Compound V2 model",
  "Lorimer Jenkins operation liquidity announcement",
  "Lorimer Jenkins three week development",
  "Lorimer Jenkins rapid protocol building",
  "Lorimer Jenkins 1,500 user waitlist growth",
  "Lorimer Jenkins $7.5 million early traction",
  "Lorimer Jenkins 415 signups two days",

  // Industry Recognition & Media Coverage
  "Lorimer Jenkins IBTimes UK feature",
  "Lorimer Jenkins VentureBeat article",
  "Lorimer Jenkins HackBee Dev-Talks interview",
  "Lorimer Jenkins Permaweb Pioneers podcast",
  "Lorimer Jenkins Medium blockchain writer",
  "Lorimer Jenkins crypto journalism",
  "Lorimer Jenkins Web3 thought leadership",
  "Lorimer Jenkins blockchain media coverage",
  "Lorimer Jenkins DeFi industry spotlight",
  "Lorimer Jenkins Arweave ecosystem leader",
  "Lorimer Jenkins crypto influencer",
  "Lorimer Jenkins Web3 podcast guest",
  "Lorimer Jenkins developer interview series",

  // Geographic & Location Keywords
  "Lorimer Jenkins UK Web3 founder",
  "Lorimer Jenkins British blockchain entrepreneur",
  "Lorimer Jenkins Cambridge based developer",
  "Lorimer Jenkins England crypto builder",
  "Lorimer Jenkins European DeFi pioneer",
  "Lorimer Jenkins London Web3 scene",
  "Lorimer Jenkins Berlin Community Labs filming",
  "Lorimer Jenkins international crypto presence",
  "Lorimer Jenkins global Arweave adoption",

  // Personal Brand Evolution
  "Lorimer Jenkins name evolution Twitter",
  "Lorimer Jenkins bio changes social media",
  "Lorimer Jenkins brand development",
  "Lorimer Jenkins LiquidOps co-founder title",
  "Lorimer Jenkins personal website launch",
  "Lorimer Jenkins social media presence",
  "Lorimer Jenkins professional evolution",
  "Lorimer Jenkins public profile growth",
  "Lorimer Jenkins thought leader emergence",

  // Unique Personal Traits & Characteristics
  "Lorimer Jenkins anti-cheese stance",
  "Lorimer Jenkins dairy-free developer",
  "Lorimer Jenkins unique personality traits",
  "Lorimer Jenkins creative problem solver",
  "Lorimer Jenkins unconventional background",
  "Lorimer Jenkins authentic Web3 builder",
  "Lorimer Jenkins relatable crypto founder",
  "Lorimer Jenkins approachable tech leader",

  // Competitive Analysis Keywords
  "Lorimer Jenkins vs Ethereum DeFi founders",
  "Lorimer Jenkins unique Arweave focus",
  "Lorimer Jenkins permanent storage advantage",
  "Lorimer Jenkins authentication innovation",
  "Lorimer Jenkins user experience priority",
  "Lorimer Jenkins accessibility focus",
  "Lorimer Jenkins bridge builder Web2 Web3",
  "Lorimer Jenkins practical DeFi solutions",
  "Lorimer Jenkins sustainable protocol design",
  "Lorimer Jenkins long-term vision crypto",

  // Community Building & Ecosystem
  "Lorimer Jenkins Community Labs first fellow",
  "Lorimer Jenkins ecosystem building",
  "Lorimer Jenkins developer mentorship",
  "Lorimer Jenkins startup ecosystem",
  "Lorimer Jenkins talent development",
  "Lorimer Jenkins open source advocacy",
  "Lorimer Jenkins collaborative development",
  "Lorimer Jenkins peer support",
  "Lorimer Jenkins knowledge sharing",
  "Lorimer Jenkins technical education",

  // Industry Trends & Innovation
  "Lorimer Jenkins AgentFi predictions",
  "Lorimer Jenkins AI DeFi integration",
  "Lorimer Jenkins autonomous finance",
  "Lorimer Jenkins permanent data storage finance",
  "Lorimer Jenkins next generation protocols",
  "Lorimer Jenkins Web3 infrastructure building",
  "Lorimer Jenkins decentralized future vision",
  "Lorimer Jenkins blockchain evolution insights",
  "Lorimer Jenkins crypto mainstream adoption",
  "Lorimer Jenkins financial sovereignty advocacy",
];
